kind: Service
apiVersion: v1
metadata:
  name: enc-busybox-service
  labels:
    name: enc-busybox-service
spec:
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  selector:
    app: encryption-busybox
  type: NodePort
  sessionAffinity: None
  externalTrafficPolicy: Cluster
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: encryption-busybox
  labels:
    app: encryption-busybox
spec:
  replicas: 2
  selector:
    matchLabels:
      app: encryption-busybox
  template:
    metadata:
      labels:
        app: encryption-busybox
    spec:
      containers:
      - name: encryption-busybox
        image: junkmail4mjd/encryption-busybox:0.2.3
        ports:
        - containerPort: 3000
          protocol: TCP
        imagePullPolicy: IfNotPresent
      - name: redis
        image: redis:3.2
        ports:
        - containerPort: 6379
          protocol: TCP
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
